version: "3"

services:
  frontend:
    image: node:20-alpine
    command: yarn start
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - REACT_APP_API_URL=https://nestjs.test.deploy.nl

    ports:
      - 3001:3000
      - 24678:24678
